# Generated by Django 5.1.5 on 2026-02-22 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("intitule", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("Planification", "Planification"),
                            ("Exécution", "Exécution"),
                            ("Clôturé", "Clôturé"),
                        ],
                        default="Planification",
                        max_length=20,
                    ),
                ),
                (
                    "budget_previsionnel",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "montant_contrat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "taux_avancement",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin_prevue", models.DateField()),
                ("archive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("champ_modifie", models.CharField(max_length=100)),
                ("ancienne_valeur", models.TextField(blank=True)),
                ("nouvelle_valeur", models.TextField(blank=True)),
                ("date_modification", models.DateTimeField(auto_now_add=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_modification"],
            },
        ),
    ]
